/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type SignalStruct = { signal: BytesLike; creationTime: BigNumberish };

export type SignalStructOutput = [signal: string, creationTime: bigint] & {
  signal: string;
  creationTime: bigint;
};

export interface ISignalingInterface extends Interface {
  getFunction(
    nameOrSignature: "getAnswer" | "getOffer" | "setAnswer" | "setOffer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "proposeAnswer" | "proposeOffer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAnswer",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAnswer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setOffer", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "getAnswer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAnswer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOffer", data: BytesLike): Result;
}

export namespace proposeAnswerEvent {
  export type InputTuple = [
    offerer: AddressLike,
    answerer: AddressLike,
    answer: SignalStruct
  ];
  export type OutputTuple = [
    offerer: string,
    answerer: string,
    answer: SignalStructOutput
  ];
  export interface OutputObject {
    offerer: string;
    answerer: string;
    answer: SignalStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace proposeOfferEvent {
  export type InputTuple = [offerer: AddressLike, offer: SignalStruct];
  export type OutputTuple = [offerer: string, offer: SignalStructOutput];
  export interface OutputObject {
    offerer: string;
    offer: SignalStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISignaling extends BaseContract {
  connect(runner?: ContractRunner | null): ISignaling;
  waitForDeployment(): Promise<this>;

  interface: ISignalingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAnswer: TypedContractMethod<
    [answerer: AddressLike, offerer: AddressLike],
    [SignalStructOutput],
    "view"
  >;

  getOffer: TypedContractMethod<
    [offerer: AddressLike],
    [SignalStructOutput],
    "view"
  >;

  setAnswer: TypedContractMethod<
    [answer: BytesLike, offerer: AddressLike],
    [void],
    "nonpayable"
  >;

  setOffer: TypedContractMethod<[offer: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAnswer"
  ): TypedContractMethod<
    [answerer: AddressLike, offerer: AddressLike],
    [SignalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<[offerer: AddressLike], [SignalStructOutput], "view">;
  getFunction(
    nameOrSignature: "setAnswer"
  ): TypedContractMethod<
    [answer: BytesLike, offerer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOffer"
  ): TypedContractMethod<[offer: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "proposeAnswer"
  ): TypedContractEvent<
    proposeAnswerEvent.InputTuple,
    proposeAnswerEvent.OutputTuple,
    proposeAnswerEvent.OutputObject
  >;
  getEvent(
    key: "proposeOffer"
  ): TypedContractEvent<
    proposeOfferEvent.InputTuple,
    proposeOfferEvent.OutputTuple,
    proposeOfferEvent.OutputObject
  >;

  filters: {
    "proposeAnswer(address,address,tuple)": TypedContractEvent<
      proposeAnswerEvent.InputTuple,
      proposeAnswerEvent.OutputTuple,
      proposeAnswerEvent.OutputObject
    >;
    proposeAnswer: TypedContractEvent<
      proposeAnswerEvent.InputTuple,
      proposeAnswerEvent.OutputTuple,
      proposeAnswerEvent.OutputObject
    >;

    "proposeOffer(address,tuple)": TypedContractEvent<
      proposeOfferEvent.InputTuple,
      proposeOfferEvent.OutputTuple,
      proposeOfferEvent.OutputObject
    >;
    proposeOffer: TypedContractEvent<
      proposeOfferEvent.InputTuple,
      proposeOfferEvent.OutputTuple,
      proposeOfferEvent.OutputObject
    >;
  };
}
