/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISignaling,
  ISignalingInterface,
} from "../../contracts/ISignaling";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "signal",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "SignalEmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "offerer",
        type: "address",
      },
    ],
    name: "getSignal",
    outputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "signal",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "creationTime",
            type: "uint256",
          },
        ],
        internalType: "struct Signal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "compressedSignal",
        type: "bytes",
      },
    ],
    name: "setSignal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISignaling__factory {
  static readonly abi = _abi;
  static createInterface(): ISignalingInterface {
    return new Interface(_abi) as ISignalingInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISignaling {
    return new Contract(address, _abi, runner) as unknown as ISignaling;
  }
}
