name: signaling_contract_sdk
description: Dart SDK for interacting with blockchain signaling smart contract.
version: 1.0.0
homepage: https://github.com/gualandi/parresia-contract
repository: https://github.com/gualandi/parresia-contract
issue_tracker: https://github.com/gualandi/parresia-contract/issues
license: LGPL-3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  web3dart: ^2.7.3
  convert: ^3.1.1

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
